//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mekg.DeviceSimulation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mekg.DeviceSimulation.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -14.049,-25.82,-21.428,-21.699,-19.698,-20.091,-18.506,-17.482,-16.254,-13.053,-12.397,-11.241,-7.0703,-0.75351,5.4457,7.0928,14.939,22.361,25.157,22.884,20.07,16.913,5.2747,-1.8365,-8.9997,-11.815,2.7718,6.1704,5.4829,9.5288,11.104,13.802,13.32,12.323,14.55,14.425,13.24,12.365,13.321,14.985,12.606,10.281,9.4884,6.6297,5.7535,8.9153,9.0771,9.8318,4.4694,6.5763,7.9439,5.4504,10.949,12.387,9.8835,9.6945,16.082,12.671,7.493,2.268,2.4162,4.0533,2.2482,-0.86093,-2.0843,-3.306,-6.1372,-5.9454,-6.9601,43.827,118.0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ecg {
            get {
                return ResourceManager.GetString("ecg", resourceCulture);
            }
        }
    }
}
